class ThemeItemSeed {
  const ThemeItemSeed({
    required this.name,
    required this.imageAsset,
    required this.colorHex,
    required this.soundAsset,
  });

  final String name;
  final String imageAsset;
  final int colorHex;
  final String soundAsset;
}

const List<ThemeItemSeed> kFoodSeeds = [
  ThemeItemSeed(name: 'Pomme' , imageAsset: 'assets/images/pomme.png', colorHex: 0xFFE57373, soundAsset: 'sounds/pomme.mp3'),
  ThemeItemSeed(name: 'Poire' , imageAsset: 'assets/images/poire.png', colorHex: 0xFFA5D6A7, soundAsset: 'sounds/poire.mp3'),
  ThemeItemSeed(name: 'Orange' , imageAsset: 'assets/images/orange.png', colorHex: 0xFFFFB74D, soundAsset: 'sounds/orange.mp3'),
  ThemeItemSeed(name: 'Citron' , imageAsset: 'assets/images/citron.png', colorHex: 0xFFFFF176, soundAsset: 'sounds/citron.mp3'),
  ThemeItemSeed(name: 'Banane' , imageAsset: 'assets/images/banane.png', colorHex: 0xFFFFD54F, soundAsset: 'sounds/banane.mp3'),
  ThemeItemSeed(name: 'Pastèque' , imageAsset: 'assets/images/pasteque.png', colorHex: 0xFF81C784, soundAsset: 'sounds/pasteque.mp3'),
  ThemeItemSeed(name: 'Raisin' , imageAsset: 'assets/images/raisin.png', colorHex: 0xFFBA68C8, soundAsset: 'sounds/raisin.mp3'),
  ThemeItemSeed(name: 'Fraise' , imageAsset: 'assets/images/fraise.png', colorHex: 0xFFEF5350, soundAsset: 'sounds/fraise.mp3'),
  ThemeItemSeed(name: 'Myrtille' , imageAsset: 'assets/images/myrtille.png', colorHex: 0xFF7986CB, soundAsset: 'sounds/myrtille.mp3'),
  ThemeItemSeed(name: 'Melon' , imageAsset: 'assets/images/melon.png', colorHex: 0xFFAED581, soundAsset: 'sounds/melon.mp3'),
  ThemeItemSeed(name: 'Ananas' , imageAsset: 'assets/images/ananas.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/ananas.mp3'),
  ThemeItemSeed(name: 'Mangue' , imageAsset: 'assets/images/mangue.png', colorHex: 0xFFFFB74D, soundAsset: 'sounds/mangue.mp3'),
  ThemeItemSeed(name: 'Noix de coco' , imageAsset: 'assets/images/noix_de_coco.png', colorHex: 0xFFD7CCC8, soundAsset: 'sounds/noix_de_coco.mp3'),
  ThemeItemSeed(name: 'Kiwi' , imageAsset: 'assets/images/kiwi.png', colorHex: 0xFF9CCC65, soundAsset: 'sounds/kiwi.mp3'),
  ThemeItemSeed(name: 'Tomate' , imageAsset: 'assets/images/tomate.png', colorHex: 0xFFE57373, soundAsset: 'sounds/tomate.mp3'),
  ThemeItemSeed(name: 'Aubergine' , imageAsset: 'assets/images/aubergine.png', colorHex: 0xFF9575CD, soundAsset: 'sounds/aubergine.mp3'),
  ThemeItemSeed(name: 'Avocat' , imageAsset: 'assets/images/avocat.png', colorHex: 0xFFAED581, soundAsset: 'sounds/avocat.mp3'),
  ThemeItemSeed(name: 'Brocoli' , imageAsset: 'assets/images/brocoli.png', colorHex: 0xFF66BB6A, soundAsset: 'sounds/brocoli.mp3'),
  ThemeItemSeed(name: 'Salade' , imageAsset: 'assets/images/salade.png', colorHex: 0xFF81C784, soundAsset: 'sounds/salade.mp3'),
  ThemeItemSeed(name: 'Concombre' , imageAsset: 'assets/images/concombre.png', colorHex: 0xFF9CCC65, soundAsset: 'sounds/concombre.mp3'),
  ThemeItemSeed(name: 'Piment' , imageAsset: 'assets/images/piment.png', colorHex: 0xFFFF7043, soundAsset: 'sounds/piment.mp3'),
  ThemeItemSeed(name: 'Maïs' , imageAsset: 'assets/images/mais.png', colorHex: 0xFFFFEE58, soundAsset: 'sounds/mais.mp3'),
  ThemeItemSeed(name: 'Carotte' , imageAsset: 'assets/images/carotte.png', colorHex: 0xFFFFA726, soundAsset: 'sounds/carotte.mp3'),
  ThemeItemSeed(name: 'Olive' , imageAsset: 'assets/images/olive.png', colorHex: 0xFF8D6E63, soundAsset: 'sounds/olive.mp3'),
  ThemeItemSeed(name: 'Ail' , imageAsset: 'assets/images/ail.png', colorHex: 0xFFD7CCC8, soundAsset: 'sounds/ail.mp3'),
  ThemeItemSeed(name: 'Oignon' , imageAsset: 'assets/images/oignon.png', colorHex: 0xFFCE93D8, soundAsset: 'sounds/oignon.mp3'),
  ThemeItemSeed(name: 'Pomme de terre' , imageAsset: 'assets/images/pomme_de_terre.png', colorHex: 0xFFA1887F, soundAsset: 'sounds/pomme_de_terre.mp3'),
  ThemeItemSeed(name: 'Pain' , imageAsset: 'assets/images/pain.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/pain.mp3'),
  ThemeItemSeed(name: 'Croissant' , imageAsset: 'assets/images/croissant.png', colorHex: 0xFFFFCA28, soundAsset: 'sounds/croissant.mp3'),
  ThemeItemSeed(name: 'Bagel' , imageAsset: 'assets/images/bagel.png', colorHex: 0xFFFFB74D, soundAsset: 'sounds/bagel.mp3'),
  ThemeItemSeed(name: 'Bretzel' , imageAsset: 'assets/images/bretzel.png', colorHex: 0xFFBCAAA4, soundAsset: 'sounds/bretzel.mp3'),
  ThemeItemSeed(name: 'Fromage' , imageAsset: 'assets/images/fromage.png', colorHex: 0xFFFFF176, soundAsset: 'sounds/fromage.mp3'),
  ThemeItemSeed(name: 'Oeuf' , imageAsset: 'assets/images/oeuf.png', colorHex: 0xFFFFF9C4, soundAsset: 'sounds/oeuf.mp3'),
  ThemeItemSeed(name: 'Bacon' , imageAsset: 'assets/images/bacon.png', colorHex: 0xFFFF8A65, soundAsset: 'sounds/bacon.mp3'),
  ThemeItemSeed(name: 'Steak' , imageAsset: 'assets/images/steak.png', colorHex: 0xFF8D6E63, soundAsset: 'sounds/steak.mp3'),
  ThemeItemSeed(name: 'Pilon de poulet' , imageAsset: 'assets/images/pilon_poulet.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/pilon_poulet.mp3'),
  ThemeItemSeed(name: 'Pizza' , imageAsset: 'assets/images/pizza.png', colorHex: 0xFFFFA726, soundAsset: 'sounds/pizza.mp3'),
  ThemeItemSeed(name: 'Burger' , imageAsset: 'assets/images/burger.png', colorHex: 0xFFA1887F, soundAsset: 'sounds/burger.mp3'),
  ThemeItemSeed(name: 'Frites' , imageAsset: 'assets/images/frites.png', colorHex: 0xFFFFD54F, soundAsset: 'sounds/frites.mp3'),
  ThemeItemSeed(name: 'Hot-dog' , imageAsset: 'assets/images/hotdog.png', colorHex: 0xFFFFB74D, soundAsset: 'sounds/hotdog.mp3'),
  ThemeItemSeed(name: 'Taco' , imageAsset: 'assets/images/taco.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/taco.mp3'),
  ThemeItemSeed(name: 'Burrito' , imageAsset: 'assets/images/burrito.png', colorHex: 0xFFBCAAA4, soundAsset: 'sounds/burrito.mp3'),
  ThemeItemSeed(name: 'Ramen' , imageAsset: 'assets/images/ramen.png', colorHex: 0xFFFFE082, soundAsset: 'sounds/ramen.mp3'),
  ThemeItemSeed(name: 'Spaghetti' , imageAsset: 'assets/images/spaghetti.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/spaghetti.mp3'),
  ThemeItemSeed(name: 'Riz' , imageAsset: 'assets/images/riz.png', colorHex: 0xFFFFF9C4, soundAsset: 'sounds/riz.mp3'),
  ThemeItemSeed(name: 'Sushi' , imageAsset: 'assets/images/sushi.png', colorHex: 0xFFE0E0E0, soundAsset: 'sounds/sushi.mp3'),
  ThemeItemSeed(name: 'Gâteau' , imageAsset: 'assets/images/gateau.png', colorHex: 0xFFF48FB1, soundAsset: 'sounds/gateau.mp3'),
  ThemeItemSeed(name: 'Glace' , imageAsset: 'assets/images/glace.png', colorHex: 0xFF80DEEA, soundAsset: 'sounds/glace.mp3'),
  ThemeItemSeed(name: 'Cookie' , imageAsset: 'assets/images/cookie.png', colorHex: 0xFFBCAAA4, soundAsset: 'sounds/cookie.mp3'),
  ThemeItemSeed(name: 'Bonbon' , imageAsset: 'assets/images/bonbon.png', colorHex: 0xFFCE93D8, soundAsset: 'sounds/bonbon.mp3'),
];

const List<ThemeItemSeed> kTransportSeeds = [
  ThemeItemSeed(name: 'Voiture' , imageAsset: 'assets/images/voiture.png', colorHex: 0xFF90CAF9, soundAsset: 'sounds/voiture.mp3'),
  ThemeItemSeed(name: 'Taxi' , imageAsset: 'assets/images/taxi.png', colorHex: 0xFFFFF176, soundAsset: 'sounds/taxi.mp3'),
  ThemeItemSeed(name: 'Bus' , imageAsset: 'assets/images/bus.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/bus.mp3'),
  ThemeItemSeed(name: 'Trolleybus' , imageAsset: 'assets/images/trolleybus.png', colorHex: 0xFFFFB74D, soundAsset: 'sounds/trolleybus.mp3'),
  ThemeItemSeed(name: 'Minibus' , imageAsset: 'assets/images/minibus.png', colorHex: 0xFFFFE082, soundAsset: 'sounds/minibus.mp3'),
  ThemeItemSeed(name: 'Ambulance' , imageAsset: 'assets/images/ambulance.png', colorHex: 0xFFEF9A9A, soundAsset: 'sounds/ambulance.mp3'),
  ThemeItemSeed(name: 'Camion de pompier' , imageAsset: 'assets/images/camion_pompier.png', colorHex: 0xFFE57373, soundAsset: 'sounds/camion_pompier.mp3'),
  ThemeItemSeed(name: 'Voiture de police' , imageAsset: 'assets/images/voiture_police.png', colorHex: 0xFF90CAF9, soundAsset: 'sounds/voiture_police.mp3'),
  ThemeItemSeed(name: 'Camion' , imageAsset: 'assets/images/camion.png', colorHex: 0xFFB0BEC5, soundAsset: 'sounds/camion.mp3'),
  ThemeItemSeed(name: 'Tracteur' , imageAsset: 'assets/images/tracteur.png', colorHex: 0xFFA5D6A7, soundAsset: 'sounds/tracteur.mp3'),
  ThemeItemSeed(name: 'Voiture de course' , imageAsset: 'assets/images/voiture_course.png', colorHex: 0xFFFF8A65, soundAsset: 'sounds/voiture_course.mp3'),
  ThemeItemSeed(name: 'Moto' , imageAsset: 'assets/images/moto.png', colorHex: 0xFFB39DDB, soundAsset: 'sounds/moto.mp3'),
  ThemeItemSeed(name: 'Scooter' , imageAsset: 'assets/images/scooter.png', colorHex: 0xFFCE93D8, soundAsset: 'sounds/scooter.mp3'),
  ThemeItemSeed(name: 'Vélo' , imageAsset: 'assets/images/velo_transport.png', colorHex: 0xFF81C784, soundAsset: 'sounds/velo_transport.mp3'),
  ThemeItemSeed(name: 'Trottinette' , imageAsset: 'assets/images/trottinette.png', colorHex: 0xFFB2DFDB, soundAsset: 'sounds/trottinette.mp3'),
  ThemeItemSeed(name: 'Skateboard' , imageAsset: 'assets/images/skateboard.png', colorHex: 0xFFA1887F, soundAsset: 'sounds/skateboard.mp3'),
  ThemeItemSeed(name: 'Patins' , imageAsset: 'assets/images/patins.png', colorHex: 0xFF80DEEA, soundAsset: 'sounds/patins.mp3'),
  ThemeItemSeed(name: 'Train' , imageAsset: 'assets/images/train.png', colorHex: 0xFFB0BEC5, soundAsset: 'sounds/train.mp3'),
  ThemeItemSeed(name: 'Métro' , imageAsset: 'assets/images/metro.png', colorHex: 0xFF90CAF9, soundAsset: 'sounds/metro.mp3'),
  ThemeItemSeed(name: 'Tram' , imageAsset: 'assets/images/tram.png', colorHex: 0xFF80CBC4, soundAsset: 'sounds/tram.mp3'),
  ThemeItemSeed(name: 'Monorail' , imageAsset: 'assets/images/monorail.png', colorHex: 0xFFB39DDB, soundAsset: 'sounds/monorail.mp3'),
  ThemeItemSeed(name: 'Train rapide' , imageAsset: 'assets/images/train_rapide.png', colorHex: 0xFF9FA8DA, soundAsset: 'sounds/train_rapide.mp3'),
  ThemeItemSeed(name: 'Téléphérique' , imageAsset: 'assets/images/telepherique.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/telepherique.mp3'),
  ThemeItemSeed(name: 'Funiculaire' , imageAsset: 'assets/images/funiculaire.png', colorHex: 0xFFA5D6A7, soundAsset: 'sounds/funiculaire.mp3'),
  ThemeItemSeed(name: 'Bateau' , imageAsset: 'assets/images/bateau_transport.png', colorHex: 0xFF81D4FA, soundAsset: 'sounds/bateau_transport.mp3'),
  ThemeItemSeed(name: 'Voilier' , imageAsset: 'assets/images/voilier.png', colorHex: 0xFF80DEEA, soundAsset: 'sounds/voilier.mp3'),
  ThemeItemSeed(name: 'Canoë' , imageAsset: 'assets/images/canoe.png', colorHex: 0xFFFFAB91, soundAsset: 'sounds/canoe.mp3'),
  ThemeItemSeed(name: 'Ferry' , imageAsset: 'assets/images/ferry.png', colorHex: 0xFF4FC3F7, soundAsset: 'sounds/ferry.mp3'),
  ThemeItemSeed(name: 'Bateau rapide' , imageAsset: 'assets/images/bateau_rapide.png', colorHex: 0xFF4DD0E1, soundAsset: 'sounds/bateau_rapide.mp3'),
  ThemeItemSeed(name: 'Ancre' , imageAsset: 'assets/images/ancre_transport.png', colorHex: 0xFF90A4AE, soundAsset: 'sounds/ancre_transport.mp3'),
  ThemeItemSeed(name: 'Avion' , imageAsset: 'assets/images/avion.png', colorHex: 0xFF90CAF9, soundAsset: 'sounds/avion.mp3'),
  ThemeItemSeed(name: 'Petit avion' , imageAsset: 'assets/images/petit_avion.png', colorHex: 0xFFB3E5FC, soundAsset: 'sounds/petit_avion.mp3'),
  ThemeItemSeed(name: 'Hélicoptère' , imageAsset: 'assets/images/helicoptere.png', colorHex: 0xFFA5D6A7, soundAsset: 'sounds/helicoptere.mp3'),
  ThemeItemSeed(name: 'Fusée' , imageAsset: 'assets/images/fusee.png', colorHex: 0xFFFF8A65, soundAsset: 'sounds/fusee.mp3'),
  ThemeItemSeed(name: 'Satellite' , imageAsset: 'assets/images/satellite.png', colorHex: 0xFFB0BEC5, soundAsset: 'sounds/satellite.mp3'),
  ThemeItemSeed(name: 'Station essence' , imageAsset: 'assets/images/station_essence.png', colorHex: 0xFFFFAB91, soundAsset: 'sounds/station_essence.mp3'),
  ThemeItemSeed(name: 'Feu tricolore' , imageAsset: 'assets/images/feu_vertical.png', colorHex: 0xFFFFF176, soundAsset: 'sounds/feu_vertical.mp3'),
  ThemeItemSeed(name: 'Feu horizontal' , imageAsset: 'assets/images/feu_horizontal.png', colorHex: 0xFFFFF176, soundAsset: 'sounds/feu_horizontal.mp3'),
  ThemeItemSeed(name: 'Arrêt de bus' , imageAsset: 'assets/images/bus_stop.png', colorHex: 0xFFCE93D8, soundAsset: 'sounds/bus_stop.mp3'),
  ThemeItemSeed(name: 'Stop' , imageAsset: 'assets/images/panneau_stop.png', colorHex: 0xFFE57373, soundAsset: 'sounds/panneau_stop.mp3'),
  ThemeItemSeed(name: 'Travaux' , imageAsset: 'assets/images/travaux.png', colorHex: 0xFFFFCC80, soundAsset: 'sounds/travaux.mp3'),
  ThemeItemSeed(name: 'Gyrophare' , imageAsset: 'assets/images/gyrophares.png', colorHex: 0xFFEF9A9A, soundAsset: 'sounds/gyrophares.mp3'),
  ThemeItemSeed(name: 'Autoroute' , imageAsset: 'assets/images/autoroute.png', colorHex: 0xFFB0BEC5, soundAsset: 'sounds/autoroute.mp3'),
  ThemeItemSeed(name: 'Voie ferrée' , imageAsset: 'assets/images/voie_ferree.png', colorHex: 0xFF90A4AE, soundAsset: 'sounds/voie_ferree.mp3'),
  ThemeItemSeed(name: 'Décollage' , imageAsset: 'assets/images/depart_avion.png', colorHex: 0xFFB3E5FC, soundAsset: 'sounds/depart_avion.mp3'),
  ThemeItemSeed(name: 'Atterrissage' , imageAsset: 'assets/images/arrivee_avion.png', colorHex: 0xFFB3E5FC, soundAsset: 'sounds/arrivee_avion.mp3'),
  ThemeItemSeed(name: 'Siège' , imageAsset: 'assets/images/siege.png', colorHex: 0xFFBCAAA4, soundAsset: 'sounds/siege.mp3'),
  ThemeItemSeed(name: 'Valise' , imageAsset: 'assets/images/valise.png', colorHex: 0xFFA1887F, soundAsset: 'sounds/valise.mp3'),
  ThemeItemSeed(name: 'Ticket' , imageAsset: 'assets/images/ticket.png', colorHex: 0xFFFFE082, soundAsset: 'sounds/ticket.mp3'),
  ThemeItemSeed(name: 'Carte' , imageAsset: 'assets/images/carte.png', colorHex: 0xFF81D4FA, soundAsset: 'sounds/carte.mp3'),
];